### ISSUE TITLE
It doesn't show on automatic1111 colab

### ISSUE THREAD

**Issue by WalidAliAlfaid** [kex0/batch-face-swap#24]
it does install but after apply and restart UI there is no Batch Face Swap script?

**Comment by 2blackbar** [comment]
yes it oesnt show locally too, its installation process is not foolproof, i guess it failed here

**Comment by nothings** [comment]
Yeah, I had to pip install mediapipe when I installed. What do you mean by "add mediapipe to requirements"? There's an install.py to install it, but I don't know how Automatic1111 is supposed to gather or run requirements of extensions. Is there a place I can just add it in the code? If so I can fix it.

**Comment by revolverocelot1** [comment]
same, hope creator can fix it.

**Comment by danielraffel** [comment]
similar issue here in automatic1111 on macOS - see the following output in terminal

Error loading script: face_detect.py
Traceback (most recent call last):
  File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/username/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/stable-diffusion-webui/extensions/batch-face-swap/scripts/face_detect.py", line 8, in <module>
    import mediapipe as mp
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

**Comment by tam9life** [comment]
To apply
1. install extension
2.
add mediapipe>=0.9.1.0 to the bottom of \stable-diffusion-webui\requirements_versions.txt 
or
pip install mediapipe

**Comment by danielraffel** [comment]
thanks! while I tried that I still don't see it appearing in scripts under the img2img tab. i am getting these messages in terminal 

Closing server running on port: 7861
Restarting UI...
Error loading script: batch_face_swap.py
Traceback (most recent call last):
  File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/username/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/stable-diffusion-webui/extensions/batch-face-swap/scripts/batch_face_swap.py", line 8, in <module>
    from bfs_utils import *
  File "/Users/username/stable-diffusion-webui/extensions/batch-face-swap/scripts/bfs_utils.py", line 6, in <module>
    import mediapipe as mp
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

Error loading script: bfs_utils.py
Traceback (most recent call last):
  File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/username/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/stable-diffusion-webui/extensions/batch-face-swap/scripts/bfs_utils.py", line 6, in <module>
    import mediapipe as mp
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

Error loading script: face_detect.py
Traceback (most recent call last):
  File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/username/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/stable-diffusion-webui/extensions/batch-face-swap/scripts/face_detect.py", line 8, in <module>
    import mediapipe as mp
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

SD-Webui API layer loaded
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.

**Comment by kex0** [comment]
please open another issue if you still have this problem
