### ISSUE TITLE
ModuleNotFoundError: No module named 'mediapipe'

### ISSUE THREAD

**Issue by ride5k** [kex0/batch-face-swap#29]
installed via extensions tab, on restart UI console displays error.  script does not appear in dropdown list.  using directml auto1111 on AMD.

Error loading script: batch_face_swap.py
Traceback (most recent call last):
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\extensions\batch-face-swap\scripts\batch_face_swap.py", line 8, in <module>
    from bfs_utils import *
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\extensions\batch-face-swap\scripts\bfs_utils.py", line 6, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

Error loading script: bfs_utils.py
Traceback (most recent call last):
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\extensions\batch-face-swap\scripts\bfs_utils.py", line 6, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

Error loading script: face_detect.py
Traceback (most recent call last):
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "T:\stablediffusion\auto111\stable-diffusion-webui-directml\extensions\batch-face-swap\scripts\face_detect.py", line 8, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

**Comment by ride5k** [comment]
also attempted manual method, when attempting step:
"Open requirements_versions.txt and add mediapipe."
could not find any txt file of that name.

**Comment by urbanyeti** [comment]
I was having the same issue on windows. Your steps lead me to getting it to work. I needed to update the "requirement_versions.txt" file in the base folder of `stable-diffusion-webui` (same folder where webui-user.bat is). After doing this I needed to quit the application and relaunch it and it seemed to work.

**Comment by rubberbaron** [comment]
I updated the manual-installl instructions to indicate where the `requirement_versions.txt` file is. I don't know why the automatic install doesn't work though.

**Comment by ride5k** [comment]
editing the requirements_version.txt solved the issue for me.

**Comment by mrgamezy** [comment]
Adding to the requirements worked here too.

**Comment by abvgdeabvgde2** [comment]
I'm having trouble getting it to work in Colab. A few months ago It was working perfectly. But now it throws an error even after `pip install mediapipe` or after putting it in reqs txt. Did someone find a solution for Colab?
`ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'`

**Comment by SorenTruelsen** [comment]
I have had this problem a month or so now. No idea how to fix it. Tried to fiddle with the requirements, but couldn't get it to work. It really is a shame, this is by far my favorite extension. 


Here is the full error code (COLAB+) as well as the build:

Error loading script: batch_face_swap.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/batch-face-swap/scripts/batch_face_swap.py", line 8, in <module>
    from bfs_utils import *
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/batch-face-swap/scripts/bfs_utils.py", line 11, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

Error loading script: bfs_utils.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/batch-face-swap/scripts/bfs_utils.py", line 11, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

Error loading script: face_detect.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/batch-face-swap/scripts/face_detect.py", line 8, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

![image](https://user-images.githubusercontent.com/7306254/230764872-0f51a97c-d5ba-45a9-af26-055091d744e7.png)

**Comment by SorenTruelsen** [comment]
Tried with a fresh gmail + COLAB account and only installed this Addon. Still got the "ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'" error. Guess it will take some digging into the code the see what's wrong .. shit .. havent programmed in 5 years and never even seen Python before, so I might stop before I even start :)

**Comment by kex0** [comment]
> Tried with a fresh gmail + COLAB account and only installed this Addon. Still got the "ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'" error. Guess it will take some digging into the code the see what's wrong .. shit .. havent programmed in 5 years and never even seen Python before, so I might stop before I even start :)

If putting `mediapipe` in `requirements_versions.txt`  (not `requirements.txt`) doesn't work then really have no idea what could be the issue.

**Comment by kex0** [comment]
![msedge_OMHEpYPmpo](https://user-images.githubusercontent.com/46696708/232167039-df401548-d8fb-4182-a212-1aab2cfdca9b.png)
![msedge_u8kkGo6wtR](https://user-images.githubusercontent.com/46696708/232167078-788b1366-955d-439e-9bc9-3e6b54fc2194.png)

**Comment by SorenTruelsen** [comment]
> > Tried with a fresh gmail + COLAB account and only installed this Addon. Still got the "ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'" error. Guess it will take some digging into the code the see what's wrong .. shit .. havent programmed in 5 years and never even seen Python before, so I might stop before I even start :)
> 
> If putting `mediapipe` in `requirements_versions.txt` (not `requirements.txt`) doesn't work then really have no idea what could be the issue.

Thanks for responding. I'll see if I will have the energy to look into the issue.

One thing I have found is that "`requirements_versions.txt`" gets overwritten by Automatic1111 all the time, so it makes a bit harder to debug. And running it on COLAB also makes it complicated, since I cant really use an IDE to test shit. 

Still ... if it works for the rest of you, it must be a "local" issue.

**Comment by Riken-Shah** [comment]
@SorenTruelsen, 
I was able to make it work on Google Colab, by manually reinstalling `mediapipe`,
```
!pip uninstall mediapipe -y 
!pip install mediapipe --user
```

**Comment by SorenTruelsen** [comment]
@Riken-Shah YOU'RE THE MAN!!!!

![image](https://user-images.githubusercontent.com/7306254/233458452-e274f283-2ba6-4766-856a-99a56484ad15.png)

It starts now without problems
