### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Agron830** [kex0/batch-face-swap#37]
Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 399, in run
    processed = script.run(p, *script_args)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\batch-face-swap\scripts\batch_face_swap.py", line 771, in run
    finishedImages = generateImages(p, facecfg, path, searchSubdir, viewResults, int(divider), howSplit, saveMask, pathToSave, saveToOriginalFolder, onlyMask, saveNoFace, overrideDenoising, overrideMaskBlur, invertMask, singleMaskPerImage, countFaces, maskSize, keepOriginalName, pathExisting, pathMasksExisting, pathToSaveExisting, selectedTab, loadGenParams, rotation_threshold)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\batch-face-swap\scripts\batch_face_swap.py", line 386, in generateImages
    masks, totalNumberOfFaces, faces_info, skip = findFaces(facecfg, image, width, height, divider, onlyHorizontal, onlyVertical, file, totalNumberOfFaces, singleMaskPerImage, countFaces, maskSize, skip)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\batch-face-swap\scripts\batch_face_swap.py", line 72, in findFaces
    landmarkHull, face_info = getFacialLandmarkConvexHull(image, rect, onlyHorizontal, divider, small_width, small_height, small_image_index, facecfg)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\batch-face-swap\scripts\face_detect.py", line 137, in getFacialLandmarkConvexHull
    height, width, channels = image.shape
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by rubberbaron** [comment]
Was this a monochrome / grayscale image? If so, I know what the fix is, but I think you can work around it by converting it to a color/RGB image in a tool like photoshop.

**Comment by Agron830** [comment]
> Was this a monochrome / grayscale image? If so, I know what the fix is, but I think you can work around it by converting it to a color/RGB image in a tool like photoshop.

Nope just a regular image. Tried on several other images as well.

**Comment by rubberbaron** [comment]
Well, I have no idea why it's happening to you and not to anybody else, but I can make the monochrome fix.

For reference until I get the fix in, OpenCV does not document this clearly anywhere to link to, but this snippet shows how OpenCV's use of numpy's `shape` is supposed to work: https://github.com/nkmk/python-snippets/blob/2d3561da9720d4140e0d052fbee14d11f4628041/notebook/opencv_size.py#L8-L19

But apparently if it's a monochrome image, instead of using a 3D array with the third dimension being only one channel long, they use a 2D array, so the tuplet unpack fails. I wrote a helper function to handle this, but I didn't hook it up everywhere.
