### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ManuLinares** [kex0/batch-face-swap#4]
```
Error completing request
Arguments: ('task(paqpxqawcfrahpt)', 5, '', '', 'None', 'None', <PIL.Image.Image image mode=RGBA size=1334x1334 at 0x7F2E7936CF40>, None, None, None, None, <PIL.Image.Image image mode=RGB size=1334x1334 at 0x7F2E7936D2D0>, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '/home/mb/stable-diffusion-webui/imgs/', '', 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, True, True, '/home/mb/stable-diffusion-webui/imgs/', False, 1, 'Both ▦', 'Generate masks', False, '', False) {}
Traceback (most recent call last):
  File "/home/mb/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/mb/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/mb/stable-diffusion-webui/modules/img2img.py", line 142, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, args)
  File "/home/mb/stable-diffusion-webui/modules/img2img.py", line 46, in process_batch
    proc = modules.scripts.scripts_img2img.run(p, *args)
  File "/home/mb/stable-diffusion-webui/modules/scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "/home/mb/stable-diffusion-webui/extensions/batch-face-swap/scripts/face_swap.py", line 408, in run
    image = Image.open(imgPath)
  File "/home/mb/stable-diffusion-webui/venv/lib/python3.10/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'img.jpg'
```

**Comment by ManuLinares** [comment]
Updated and restarted, now it works. Idk
