### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

### ISSUE THREAD

**Issue by AncalagonX** [kex0/batch-face-swap#5]
I updated batch-face-swap to https://github.com/kex0/batch-face-swap/commit/8ca92d84920a384fda04c5a85c694fb4c1949bc7 and also restarted my entire automatic1111 stable diffusion process, but I'm still getting the same error as earlier today:

```
Traceback (most recent call last):
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\+++Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\+++Stable Diffusion\stable-diffusion-webui\extensions\batch-face-swap\scripts\face_swap.py", line 207, in generateMasks
    allFiles = [os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

**Comment by AncalagonX** [comment]
My workflow is simply:

1. Start automatic1111
2. Open a new browser tab and go to localhost:port
3. Drag an image into the top half of `Inpaint upload`
4. Scroll down and select the `batch-face-swap` script
5. Hit "Generate Masks"

**Comment by kex0** [comment]
You have to put the path to the image/images in the script itself. and then hit "Generate masks". You can save the generated masks by checking the "Save masks to disk" checkbox. 

![chrome_XmEYNaIhVq](https://user-images.githubusercontent.com/46696708/213211517-f63e813b-2e48-4f12-abef-a2b4b09eba61.png)

Sorry for the confusion. I'll think of how to make this more clear.

**Comment by AncalagonX** [comment]
> You have to put the path to the directory containing the image/images in the script itself. and then hit "Generate masks". You can save the generated masks by checking the "Save masks to disk" checkbox.
> 
> ![chrome_XmEYNaIhVq](https://user-images.githubusercontent.com/46696708/213211517-f63e813b-2e48-4f12-abef-a2b4b09eba61.png)
> 
> Sorry for the confusion. I'll think of how to make this more clear.

Since I had an image already inserted into Inpaint Upload, I thought it didn't need a directory. It does start working when I put the directory there.

**Comment by kex0** [comment]
Sorry for the late reply.

It is now possible to use images inserted into Inpaint Upload directly.
d83b961da1b3ef5a18e1b540a5538e52557aec20 

Thank you for the suggestion!
