### ISSUE TITLE
It doesnt work for a1111 1.5.1

### ISSUE THREAD

**Issue by ningnongg** [kex0/batch-face-swap#76]
I jsut updated the webui for sdxl 1.0 but after i tried it with other models which i have batch face swap turned on as a default, it just doesnt work normally when it's reached 100% it would go on to replace the facebut in this case it just doesnt.

it also shows an error message (at the starting of generation, not when the generation has reached 100%);

*** Error running postprocess: D:\.ai\stable-diffusion-webui-1.5.1\extensions\batch-face-swap\scripts\batch_face_swap.py
    Traceback (most recent call last):
      File "D:\.ai\stable-diffusion-webui-1.5.1\modules\scripts.py", line 551, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\.ai\stable-diffusion-webui-1.5.1\extensions\batch-face-swap\scripts\batch_face_swap.py", line 1004, in postprocess
        finishedImages = generateImages(p, facecfg, input_image, input_path, searchSubdir, viewResults, int(divider), howSplit, saveMask, output_path, saveToOriginalFolder, onlyMask, saveNoFace, overridePrompt, bfs_prompt, bfs_nprompt, overrideSampler, sd_sampler, overrideModel, sd_model, overrideDenoising, denoising_strength, overrideMaskBlur, mask_blur, overridePadding, inpaint_full_res_padding, overrideSeed, overrideSteps, steps, overrideCfgScale, cfg_scale, overrideSize, bfs_width, bfs_height, invertMask, singleMaskPerImage, countFaces, maskWidth, maskHeight, keepOriginalName, pathExisting, pathMasksExisting, output_pathExisting, selectedTab, mainTab, loadGenParams, rotation_threshold)
      File "D:\.ai\stable-diffusion-webui-1.5.1\extensions\batch-face-swap\scripts\batch_face_swap.py", line 464, in generateImages
        masks, totalNumberOfFaces, faces_info, skip = findFaces(facecfg, image, width, height, divider, onlyHorizontal, onlyVertical, file, totalNumberOfFaces, singleMaskPerImage, countFaces, maskWidth, maskHeight, skip)
      File "D:\.ai\stable-diffusion-webui-1.5.1\extensions\batch-face-swap\scripts\batch_face_swap.py", line 93, in findFaces
        faceRects = getFaceRectanglesYuNet(small_image, known_face_rects)
      File "D:\.ai\stable-diffusion-webui-1.5.1\extensions\batch-face-swap\scripts\face_detect.py", line 311, in getFaceRectanglesYuNet
        _, faces = face_detector.detect(img_array)
    cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'
    
I really do want this to be fixed because there are features here that i prefer way more than adetailer, i jsut can't live without it.... please help

**Comment by kex0** [comment]
Sadly I won't be able to fix this until I come back from vacation :(

**Comment by ningnongg** [comment]
> Sadly I won't be able to fix this until I come back from vacation :(

its okay now, i tried changing the detector to mediapipe (the fastest one), you might just make an announcement for that)

thanks for replying so quickly *v*

**Comment by rchennault-exelixis** [comment]
Switching to mediapipe worked for me as well.

**Comment by Jonseed** [comment]
Thanks for the comments about switching to mediapipe. That does seem to make it work again. Really wish this extension was still maintained, as it works quite differently than adetailer or reactor...

**Comment by kex0** [comment]
> Thanks for the comments about switching to mediapipe. That does seem to make it work again. Really wish this extension was still maintained, as it works quite differently than adetailer or reactor...

Hey, how is this different from adetailer?

**Comment by Jonseed** [comment]
@kex0 adetailer and reactor don't work on an entire folder of images, from what I can tell. Or maybe I'm just not using it right?

Ah, gotcha. I don't actually know because I switched to ComfyUI quite a long time ago for everything except inpainting. 
In there you can do batch processing for both BFS/adetailer and reactor/roop methods.

But knowing this, I might look into this error and potentially add better face detector.

**Comment by Jonseed** [comment]
@kex0 I'll see if I can use adetailer in img2img "batch" mode...

**Comment by Jonseed** [comment]
@kex0 I think I finally got adetailer to work like batch-face-swap in Auto's "batch" mode.

You have to set it to regular img2img "batch" mode, which is in the img2img tab. In the batch settings, you put an input directory _only_ (and output, if you like). _Don't_ put an inpaint batch mask directory (to put it into inpainting batch mode, even though inpainting is what we want to do, because we don't have all the inpainting masks prepared beforehand). Now, you have to set the regular denoising strength to 0, or it will try to regenerate the entire image via img2img. But with the denoising at 0, it will basically skip the img2img step, and move straight to adetailer. Also make sure to set the "resize by" to 1, so it doesn't try to resize the image. Make sure to set up all the adetailer settings as normal, especially check "inpaint only masked" in adetailer's settings, including adetailer's inpaint denoising strength (I set mine to 0.45), and make sure adetailer is "enabled."

With the settings set up this way, it seems to work similarly to batch-face-swap.
